- name: Install Python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Prerequisites
  ansible.builtin.import_tasks:
    file: app-preq.yml

- name: Download Python Dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Service Setup
  ansible.builtin.import_tasks:
    file: systemd-setup.yml
